use Mavenmovies;

-- total number of rentals made in the Sakila database.
select count(rental_id) as Total_no_of_rentals from rental;

-- average rental duration (in days) of movies rented from the Sakila database.
select avg(rental_duration) as Avegare_rental_duration from film;

-- First name and last name of customers in uppercase
select upper(first_name),(last_name) from customer;

-- Extract the month from the rental date and display it alongside the rental ID
select rental_id,month(rental_date) from rental;

-- Retrieve the count of rentals for each customer (display customer ID and the count of rentals)
select customer_id,count(rental_id) from rental group by customer_id;

-- total revenue generated by each store
select sum(amount) from payment group by staff_id;

-- Display the title of the movie, customer's first name, and last name who rented it
select title,first_name,last_name from film inner join inventory on film.film_id=inventory.film_id 
inner join customer on customer.store_id=inventory.store_id;

-- names of all actors who have appeared in the film "Gone with the Wind"
-- Note there is no film title "Gone with the Wind",I am taking "Academy Dinosaur".
select first_name,last_name from actor inner join film_actor on actor.actor_id = film_actor.actor_id
inner join film on film.film_id=film_actor.film_id where title='ACADEMY DINOSAUR';

-- Determine the total number of rentals for each category of movies
select count(c.name),c.name from category c inner join film_category f on c.category_id=f.category_id 
inner join film fl on f.film_id=fl.film_id group by c.name;

-- average rental rate of movies in each language
select avg(rental_rate), l.name from film f inner join language l on f.language_id=l.language_id group by l.name;

-- Retrieve the customer names along with the total amount they've spent on rentals
select c.customer_id,c.first_name,c.last_name,sum(amount) from customer c join rental r on c.customer_id=r.customer_id 
inner join payment p on r.rental_id=p.rental_id group by c.customer_id;

-- List the titles of movies rented by each customer in a particular city (e.g., 'London').
select c.customer_id,c.first_name,c.last_name,f.title from customer c join rental r on c.customer_id=r.customer_id
join inventory i on r.inventory_id=i.inventory_id
join film f on i.film_id=f.film_id
join store s on i.store_id=s.store_id
join address a on c.address_id=a.address_id
join city ci on a.city_id=ci.city_id
where ci.city='London';

-- Display the top 5 rented movies along with the number of times they've been rented
SELECT 
    COUNT(rental_id), f.title
FROM
    film f
        INNER JOIN
    inventory i ON f.film_id = i.film_id
        INNER JOIN
    rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY COUNT(rental_rate) DESC
LIMIT 5;

-- Determine the customers who have rented movies from both stores (store ID 1 and store ID 2)
select c.customer_id,c.first_name,c.last_name from customer c inner join rental r on c.customer_id=r.customer_id
inner join	inventory i on r.inventory_id=i.inventory_id 
inner join store s on i.store_id=s.store_id where s.store_id in (1,2) group by c.customer_id,c.first_name,c.last_name
having count(distinct s.store_id)=2;




